name: 'gsc_trade_disrupt_elt'
version: '1.0.0'

profile: 'gsc_trade_disrupt_elt'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  gsc_trade_disrupt_elt:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      core:
        +materialized: table

      reporting:
        +materialized: table