name: 'gsc_trade_disrupt'
version: '1.0.0'
config-version: 2

profile: 'gsc_trade_disrupt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gsc_trade_disrupt:

    staging:
      +materialized: view

    marts:
      +materialized: table

seeds:
  gsc_trade_disrupt:
    +quote_columns: false